[project]
name = "Wound-Border-Characterization"
version = "1.0.0"
authors = [
    { name="Sameera Viraj", email="mpsviraj@gmail.com" },
]
description = "A pipeline for 3D analysis and classification of chronic wound border morphology."
readme = "README.md"
requires-python = "~=3.10"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy==2.2.6",
    "pandas==2.2.3",
    "scikit-learn==1.6.1",
    "scikit-image==0.25.2",
    "scipy==1.15.2",
    "pacmap==0.8.0",
    "hdbscan==0.8.40",
    "joblib==1.5.0",
    "matplotlib==3.10.3",
    "seaborn==0.13.2",
    "tqdm==4.67.1",
    "opencv-python==4.11.0.86",
    "pillow==11.2.1",
]

[project.optional-dependencies]
dev = [
    "pytest==8.4.1",
    "pytest-cov",
]

[project.scripts]
wound-analyzer = "wound_analyzer.run_pipeline:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(levelname)s %(message)s"
log_file = "pytest_logs.log"
log_file_level = "DEBUG"
log_file_format = "%(asctime)s %(levelname)s %(message)s"
pythonpath = ["."]
testpaths = ["tests"]